server:
  port: 8083
  reactive:
    type: netty

spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/proselyte
    username: user
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/proselyte
    user: user
    password: password
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    defaultModelsExpandDepth: -1

jwt:
  password:
    encoder:
      secret : FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration : 64
      keyLength : 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration : 3600
  issuer : Ruslan


cloud:
  aws:
    credentials:
      access-key: AKIA5FTZB3BXWRKYQJ74
      secret-key: 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
    region:
      static: eu-central-1
    stack:
      auto: false

servlet:
  multipart:
    max-file-size: 50MB
    max-request-size: 100MB

application:
  bucket:
    name: proselytefiles

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.http: DEBUG

