create table users
(
    id       int generated by default as identity primary key,
    username varchar(255)  not null unique,
    password varchar(2048) not null,
    role     varchar(32)   not null,
    status   varchar(32)   not null
);