CREATE TABLE files
(
    id        int generated by default as identity primary key,
    name      varchar(255)  not null unique,
    location varchar(2048) not null unique,
    status varchar(255) not null

);